# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afa50f5c9a4466334b46f7d748823a5490bfdec3e9980b28d4586c5f5f1637fe234abf5d0661f7dd08e6c6bf8c7bdec1cc6943e4d75cfc709b1544cd7ca13ae9

test:
  secret_key_base: b36ac351cb67157b8f188f724f2bc8d05d7aef1452ff58a158945f1f86e06167790dbb3e53ede6ffa11bbf1741dd505eca8f1cb5c427b1535de2cc06698fa9e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
