# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fbba1054512a156fde07a1b416049a386a4dc90813815f909d2b90221da72ea70a4eccc539868dd2c576fe87bd941a715641e2aa7f9320abd4cb04295051c27

test:
  secret_key_base: 4d1c8e4c0e96c2860abb5c0d2d11dc2b7f7565a438a13a26a21ab68050ed3c325b274058a540a34d1cd7e8be58e41386ef08228c02a2ae3296194f50e518f758

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
